import { IMovieCarousel } from "@/commons/common";
import Breadcrumb from "@/components/Breadcrumb";
import Container from "@/components/Container";
import MovieCarousel from "@/components/MovieCarousel";
import StyledBreadcrumblink from "@/components/StyledBreadcrumbLink";
import VideoJS from "@/components/Videojs/Videojs";
import BaseLayout from "@/layouts/BaseLayout";
import { pagesInfo } from "@/pagesInfo";
import { pageStyles } from "@/styles/styles.config";
import { HomeOutlined } from "@ant-design/icons";
import { Rate, Space } from "antd";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { ReactElement, useRef } from "react";
import styled from "styled-components";
import { NextPageWithLayout } from "../_app";
import { PlayIcon } from "@/icons";
import ServerList from "@/components/ServerList";
const DetailPage: NextPageWithLayout = () => {
    const playerRef = useRef(null);
    const videoJsOptions = {
        autoplay: false,
        controls: true,
        responsive: true,
        fluid: true,
        sources: [{
            src: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
            type: 'video/mp4'
        }],
        poster: 'https://xemphim123.com/storage/images/ve-binh-dai-ngan-ha-3/ve-binh-dai-ngan-ha-3-thumb.jpg',

        plugins: {
            hotkeys: {
                volumeStep: 0.1,
                fullscreenKey: function (event, player) {
                    // override fullscreen to trigger when pressing the F key or Ctrl+Enter
                    return ((event.which === 70) || (event.ctrlKey && event.which === 13));
                },

            },
        },

        playbackRates: [0.5, 1, 1.5, 2],
    };

    const handlePlayerReady = (player) => {
        playerRef.current = player;

        // You can handle player events here, for example:
        player.on('waiting', () => {
            videojs.log('player is waiting');
        });

        player.on('dispose', () => {
            videojs.log('player will dispose');
        });
    };
    const iMovieCarousel: IMovieCarousel = {
        centerMode: false,
        slidesToShow: 4,
        iCatalogInfo: {
            title: 'movie category',
            description: 'lorem ipsum is sunoly dummy text of printing and ypesettings'
        }
    }
    const router = useRouter();
    const { movieID } = router.query;
    var key = 1;
    const breadcrumbItems: Array<React.ReactNode> = [
        <StyledBreadcrumblink key={key++} href='/'>
            <Space>
                <HomeOutlined />
                <span>Xem Phim</span>
            </Space>
        </StyledBreadcrumblink>,
        <StyledBreadcrumblink key={key++} href='/'>phim chiếu rạp</StyledBreadcrumblink>,
        <span key={key++} style={{ color: pageStyles.activeColor }}>Avatar</span>,
    ]
    return (
        <>
            <Head>
                <title>{pagesInfo.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Breadcrumb items={breadcrumbItems} />
            <Container>
                <WatchWrapper>
                    <VideoJS options={videoJsOptions} onReady={handlePlayerReady} />
                </WatchWrapper>
                <ServerList />
                <CommonInfoWrapper>
                    <AvatarWrapper>
                        <img src="https://xemphim123.com/storage/images/ve-binh-dai-ngan-ha-3/ve-binh-dai-ngan-ha-3-thumb.jpg" alt="" />
                    </AvatarWrapper>
                    <InfoWrapper>
                        <Title>Avatar (2009)</Title>
                        <label>Intro</label>
                        <p>Bởi khủng hoảng năng lượng, một số tập đoàn năng lượng quyết định đầu tư …xâm lược một hành tinh khác để khai thác những khoáng sản quý giá có thể giải quyết vấn đề khủng hoảng. Jake, một cựu binh thủy quân lục chiến được giao nhiệm vụ thâm nhập vào cộng đồng dân cư bản địa để thu thập tin tức thuận lợi cho kế hoạch tấn công. Tuy nhiên, những ngày sống tại Pandora đã thay đổi nhận thức của Jake về thế giới. Anh muốn cứu Pantera khỏi những kẻ tham lam, tránh vận mệnh u ám của Trái Đất.</p>
                        {/* <Space> */}
                        <div>
                            <p><b>Thể loại: </b><span>hành động, phiêu lưu</span></p>
                            <p><b>Chất Lượng: </b><span>HD</span></p>
                            <p><b>Thời Lượng: </b><span>120 phút</span></p>
                            <p><b>Năm Phát Hành: </b><span>2022</span></p>
                            <p><b>Quốc Gia: </b><span>Âu mỹ</span></p>
                            <p><span>104.3k</span> Lượt Xem</p>
                            <p><PlayIcon></PlayIcon> Xem Trailer</p>
                        </div>
                              
                        {/* </Space> */}
                      
                    </InfoWrapper>
                </CommonInfoWrapper>
            </Container>
            <MovieCarousel {...iMovieCarousel} />
            <Title>Phim liên quan</Title>
        </>
    );
}

const InfoWrapper = styled.div`
    width: 82%;

    div {
        display: flex;
        width: 100%;
        flex-wrap: wrap;
        
        p {
            width: 30%;

            span {
                color: ${pageStyles.activeColor};
            }
        }
    }
`
const AvatarWrapper = styled.div`
    border-radius: 1rem;
    width: 15%;
    overflow: hidden;
    
    img {
        width : 100%;
    }
`
const WatchWrapper = styled.div`
    min-height: 35rem;
`

const CommonInfoWrapper = styled.div`
    margin-top: 2rem;
    background-color: ${pageStyles.textColor2};
    border-radius: 1rem;

    display: flex;
    padding: 1rem;

    flex-wrap: wrap;
    gap: 2rem;

    label {
        font-size: 1.25rem;
        font-weight: 400;
        margin-bottom: 0.5rem;
        display: block;
    }

    p {
        line-height: 1.5rem;
        font-size: 17px;
        font-weight: 300;
    }
`

const Title = styled.h3`
    color: green;
    font-size: 2rem;

`
DetailPage.getLayout = function getLayout(page: ReactElement) {
    return (
        <BaseLayout>
            {page}
        </BaseLayout>
    )
}

export default DetailPage;