import { IMovieCarousel } from "@/commons/common";
import Container from "@/components/Container";
import MovieCarousel from "@/components/MovieCarousel";
import Pagination from "@/components/Pagination";
import ProductGridItem from "@/components/ProductGridItem";
import Title from "@/components/Title";
import BaseLayout from "@/layouts/BaseLayout";
import { pagesInfo } from "@/pagesInfo";
import { Col, Row } from "antd";
import Head from "next/head";
import { useRouter } from "next/router";
import { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";

const DetailPage: NextPageWithLayout = () => {
    const iMovieCarousel: IMovieCarousel = {
        centerMode: false,
        slidesToShow: 4,
        iCatalogInfo: {
            title: 'movie category',
            description: 'lorem ipsum is sunoly dummy text of printing and ypesettings'
        }
    }
    const router = useRouter();
    const {movieID} = router.query;
    console.log("movieID = ",movieID);
    const rowStyled :React.CSSProperties = {
        marginTop:'1.75rem',
        marginBottom:'1.75rem',
      }
      
    return (
        <>
            <Head>
                <title>{pagesInfo.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <Title>Phim lẻ nổi bật</Title>
            <Row gutter={[16,16]} style={rowStyled}>
              <Col span={6}><ProductGridItem link='/info/abc123' /></Col>
              <Col span={6}><ProductGridItem link='/info/abc123' /></Col>
              <Col span={6}><ProductGridItem link='/info/abc123' /></Col>
              <Col span={6}><ProductGridItem link='/info/abc123' /></Col>
              <Col span={6}><ProductGridItem link='/info/abc123' /></Col>
              <Col span={6}><ProductGridItem link='/info/abc123' /></Col>
              <Col span={6}><ProductGridItem link='/info/abc123' /></Col>
        
            </Row> 
            <Pagination />
            </Container>
            <MovieCarousel {...iMovieCarousel} />
        </>
    );
}

DetailPage.getLayout = function getLayout(page: ReactElement) {
    return (
        <BaseLayout>
            {page}
        </BaseLayout>
    )
}

export default DetailPage;