import { IMovieCarousel } from "@/commons/common";
import Breadcrumb from "@/components/Breadcrumb";
import Container from "@/components/Container";
import MovieCarousel from "@/components/MovieCarousel";
import Pagination from "@/components/Pagination";
import ProductGridItem from "@/components/ProductGridItem";
import StyledBreadcrumblink from "@/components/StyledBreadcrumbLink";
import Title from "@/components/Title";
import BaseLayout from "@/layouts/BaseLayout";
import { pagesInfo } from "@/pagesInfo";
import { HomeOutlined } from "@ant-design/icons";
import { Col, Row, Space } from "antd";
import Head from "next/head";
import { useRouter } from "next/router";
import { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";

const DetailPage: NextPageWithLayout = () => {
    const iMovieCarousel: IMovieCarousel = {
        centerMode: false,
        slidesToShow: 4,
        iCatalogInfo: {
            title: 'movie category',
            description: 'lorem ipsum is sunoly dummy text of printing and ypesettings'
        }
    }
    const router = useRouter();
    const { movieID } = router.query;

    const rowStyled: React.CSSProperties = {
        marginTop: '1.75rem',
        marginBottom: '1.75rem',
    }

    const breadcrumbItems: Array<React.ReactNode> = [
        <StyledBreadcrumblink href='/'>
            <Space>
                <HomeOutlined />
                <span>Xem Phim</span>
            </Space>
        </StyledBreadcrumblink>,
        <span>Danh sách phim chiếu rạp mới</span>,
    ]

    return (
        <>
            <Head>
                <title>{pagesInfo.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Breadcrumb items={breadcrumbItems} />
            <Container>

                <Title>Phim lẻ nổi bật</Title>
                <Row gutter={[16, 16]} style={rowStyled}>
                    <Col span={4}><ProductGridItem link='/info/abc123' /></Col>
                    <Col span={4}><ProductGridItem link='/info/abc123' /></Col>
                    <Col span={4}><ProductGridItem link='/info/abc123' /></Col>
                    <Col span={4}><ProductGridItem link='/info/abc123' /></Col>
                    <Col span={4}><ProductGridItem link='/info/abc123' /></Col>
                    <Col span={4}><ProductGridItem link='/info/abc123' /></Col>
                    <Col span={4}><ProductGridItem link='/info/abc123' /></Col>

                </Row>
                <Pagination />
            </Container>
            <MovieCarousel {...iMovieCarousel} />
        </>
    );
}

DetailPage.getLayout = function getLayout(page: ReactElement) {
    return (
        <BaseLayout>
            {page}
        </BaseLayout>
    )
}

export default DetailPage;