import HomeLayout from '@/layouts/HomeLayout'
import Head from 'next/head'
import { ReactElement } from 'react'
import type { NextPageWithLayout } from './_app'
import {pagesInfo} from '@/pagesInfo';
const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>{pagesInfo.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <HomeLayout>
      {page}
    </HomeLayout>
  )
}
 
export default Home;